version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Mount the current directory for development (optional)
      - .:/app
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - LOGLEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/?healthz=true"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - streamlit-network

networks:
  streamlit-network:
    driver: bridge

volumes:
  logs:
    driver: local
